Remove npx -n usage in favor of cross-env / NODE_OPTIONS
graphile/starter pull request #230
Opened 2021-01-09 06:06 UTC by DylanVann

## Description

On cloning this repo and following instructions I encountered errors saying `-n` is no longer supported in `npx`.

![image](https://user-images.githubusercontent.com/1537615/104084579-57c1aa00-5216-11eb-8f86-ccde022ec116.png)

It seems that my version of `npx` is too old to work correctly. I normally use `fnm` to manage Node versions and don't use `npm` or `npx` too often so I hadn't noticed this.

This could be mitigated for other users by using `NODE_OPTIONS` instead of `npx`.

## Performance impact

Possibly slightly better perf 🤷‍♂️ , most of these commands were already using `cross-env`.

## Security impact

None.

## Checklist

- [x] My code matches the project's code style and `yarn lint:fix` passes.
- [x] I've added tests for the new feature, and `yarn test` passes.
- [x] I have detailed the new feature in the relevant documentation.
- [x] I have added this feature to 'Pending' in the `RELEASE_NOTES.md` file (if one exists).
- [x] If this is a breaking change I've explained why.

2021-01-09 08:53 UTC, benjie commented
Do you know if this still works on Windows? That’s why we had to do the npx stuff iirc.

2021-01-10 05:34 UTC, DylanVann commented
I believe it should because it's making use of `cross-env`. `NODE_OPTIONS` should work on Windows.

After trying to get a Windows dev environment working in VirtualBox for over 2 hours I'm calling it quits, maybe someone else can test.

Not sure what it does exactly, but the fact that "Windows Node CI" is passing seems to be a good sign.

2021-01-11 10:33 UTC, benjie commented
Awesome; thanks for checking @DylanVann. We seem to be having some CI issue but they look transient, so I'll trigger a rebuild and see if we can get them to pass.

2021-01-11 11:34 UTC, benjie requested changes
Looks good; the main issue is the production docker build fails because the worker fails to start (so cannot be torn down); I believe this is because `cross-env` needs to be a production dependency within the worker now. We ought to do the same for `@app/db`.

2021-01-11 11:34 UTC, benjie commented on @app/worker/package.json
> +    "gw": "cd dist && cross-env NODE_OPTIONS=\"$NODE_OPTIONS -r @app/config/env\" graphile-worker",
To use `cross-env` here, we need to move it from `devDependencies` to `dependencies`.

2021-01-11 11:34 UTC, benjie commented on @app/db/package.json
> +    "gm": "cross-env NODE_OPTIONS=\"$NODE_OPTIONS -r @app/config/env\" graphile-migrate",
To use cross-env here we should move it to `dependencies`.

2021-01-11 14:55 UTC, DylanVann commented
That did the trick, thanks!

2021-01-11 18:16 UTC, merged

2021-01-11 18:17 UTC, benjie commented
Awesome; thanks! :raised_hands: